apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
  labels:
    app: netflix-app
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-app
      version: v1
  template:
    metadata:
      labels:
        app: netflix-app
        version: v1
    spec:
      containers:
      - name: netflix-app
        image: paraspahwa/netflix:latest
        ports:
        - containerPort: 80
