apiVersion: v1
kind: service 
metadata:
  name: netflix-app
  labels:
    app: netflix-app
    version: v1
spec:
  selector:
    app: netflix-app
    version: v1
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080